version: 2.0
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    excecutor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
